
CREATE TABLE IF NOT EXISTS `countries` (
  `id` char(3) NOT NULL DEFAULT '',
  `name` char(55) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` char(2) NOT NULL DEFAULT '',
  PRIMARY KEY (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


INSERT INTO `countries` (`id`, `name`, `code`) VALUES
('AFG', 'Afghanistan', 'AF'),
('NLD', 'Netherlands', 'NL'),
('ANT', 'Netherlands Antilles', 'AN'),
('ALB', 'Albania', 'AL'),
('DZA', 'Algeria', 'DZ'),
('ASM', 'American Samoa', 'AS'),
('AND', 'Andorra', 'AD'),
('AGO', 'Angola', 'AO'),
('AIA', 'Anguilla', 'AI'),
('ATG', 'Antigua and Barbuda', 'AG'),
('ARE', 'United Arab Emirates', 'AE'),
('ARG', 'Argentina', 'AR'),
('ARM', 'Armenia', 'AM'),
('ABW', 'Aruba', 'AW'),
('AUS', 'Australia', 'AU'),
('AZE', 'Azerbaijan', 'AZ'),
('BHS', 'Bahamas', 'BS'),
('BHR', 'Bahrain', 'BH'),
('BGD', 'Bangladesh', 'BD'),
('BRB', 'Barbados', 'BB'),
('BEL', 'Belgium', 'BE'),
('BLZ', 'Belize', 'BZ'),
('BEN', 'Benin', 'BJ'),
('BMU', 'Bermuda', 'BM'),
('BTN', 'Bhutan', 'BT'),
('BOL', 'Bolivia', 'BO'),
('BIH', 'Bosnia and Herzegovina', 'BA'),
('BWA', 'Botswana', 'BW'),
('BRA', 'Brazil', 'BR'),
('GBR', 'United Kingdom', 'GB'),
('VGB', 'Virgin Islands, British', 'VG'),
('BRN', 'Brunei', 'BN'),
('BGR', 'Bulgaria', 'BG'),
('BFA', 'Burkina Faso', 'BF'),
('BDI', 'Burundi', 'BI'),
('CYM', 'Cayman Islands', 'KY'),
('CHL', 'Chile', 'CL'),
('COK', 'Cook Islands', 'CK'),
('CRI', 'Costa Rica', 'CR'),
('DJI', 'Djibouti', 'DJ'),
('DMA', 'Dominica', 'DM'),
('DOM', 'Dominican Republic', 'DO'),
('ECU', 'Ecuador', 'EC'),
('EGY', 'Egypt', 'EG'),
('SLV', 'El Salvador', 'SV'),
('ERI', 'Eritrea', 'ER'),
('ESP', 'Spain', 'ES'),
('ZAF', 'South Africa', 'ZA'),
('ETH', 'Ethiopia', 'ET'),
('FLK', 'Falkland Islands', 'FK'),
('FJI', 'Fiji Islands', 'FJ'),
('PHL', 'Philippines', 'PH'),
('FRO', 'Faroe Islands', 'FO'),
('GAB', 'Gabon', 'GA'),
('GMB', 'Gambia', 'GM'),
('GEO', 'Georgia', 'GE'),
('GHA', 'Ghana', 'GH'),
('GIB', 'Gibraltar', 'GI'),
('GRD', 'Grenada', 'GD'),
('GRL', 'Greenland', 'GL'),
('GLP', 'Guadeloupe', 'GP'),
('GUM', 'Guam', 'GU'),
('GTM', 'Guatemala', 'GT'),
('GIN', 'Guinea', 'GN'),
('GNB', 'Guinea-Bissau', 'GW'),
('GUY', 'Guyana', 'GY'),
('HTI', 'Haiti', 'HT'),
('HND', 'Honduras', 'HN'),
('HKG', 'Hong Kong', 'HK'),
('SJM', 'Svalbard and Jan Mayen', 'SJ'),
('IDN', 'Indonesia', 'ID'),
('IND', 'India', 'IN'),
('IRQ', 'Iraq', 'IQ'),
('IRN', 'Iran', 'IR'),
('IRL', 'Ireland', 'IE'),
('ISL', 'Iceland', 'IS'),
('ISR', 'Israel', 'IL'),
('ITA', 'Italy', 'IT'),
('TMP', 'East Timor', 'TP'),
('AUT', 'Austria', 'AT'),
('JAM', 'Jamaica', 'JM'),
('JPN', 'Japan', 'JP'),
('YEM', 'Yemen', 'YE'),
('JOR', 'Jordan', 'JO'),
('CXR', 'Christmas Island', 'CX'),
('YUG', 'Yugoslavia', 'YU'),
('KHM', 'Cambodia', 'KH'),
('CMR', 'Cameroon', 'CM'),
('CAN', 'Canada', 'CA'),
('CPV', 'Cape Verde', 'CV'),
('KAZ', 'Kazakstan', 'KZ'),
('KEN', 'Kenya', 'KE'),
('CAF', 'Central African Republic', 'CF'),
('CHN', 'China', 'CN'),
('KGZ', 'Kyrgyzstan', 'KG'),
('KIR', 'Kiribati', 'KI'),
('COL', 'Colombia', 'CO'),
('COM', 'Comoros', 'KM'),
('COG', 'Congo', 'CG'),
('COD', 'Congo, The Democratic Republic of the', 'CD'),
('CCK', 'Cocos (Keeling) Islands', 'CC'),
('PRK', 'North Korea', 'KP'),
('KOR', 'South Korea', 'KR'),
('GRC', 'Greece', 'GR'),
('HRV', 'Croatia', 'HR'),
('CUB', 'Cuba', 'CU'),
('KWT', 'Kuwait', 'KW'),
('CYP', 'Cyprus', 'CY'),
('LAO', 'Laos', 'LA'),
('LVA', 'Latvia', 'LV'),
('LSO', 'Lesotho', 'LS'),
('LBN', 'Lebanon', 'LB'),
('LBR', 'Liberia', 'LR'),
('LBY', 'Libyan Arab Jamahiriya', 'LY'),
('LIE', 'Liechtenstein', 'LI'),
('LTU', 'Lithuania', 'LT'),
('LUX', 'Luxembourg', 'LU'),
('ESH', 'Western Sahara', 'EH'),
('MAC', 'Macao', 'MO'),
('MDG', 'Madagascar', 'MG'),
('MKD', 'Macedonia', 'MK'),
('MWI', 'Malawi', 'MW'),
('MDV', 'Maldives', 'MV'),
('MYS', 'Malaysia', 'MY'),
('MLI', 'Mali', 'ML'),
('MLT', 'Malta', 'MT'),
('MAR', 'Morocco', 'MA'),
('MHL', 'Marshall Islands', 'MH'),
('MTQ', 'Martinique', 'MQ'),
('MRT', 'Mauritania', 'MR'),
('MUS', 'Mauritius', 'MU'),
('MYT', 'Mayotte', 'YT'),
('MEX', 'Mexico', 'MX'),
('FSM', 'Micronesia, Federated States of', 'FM'),
('MDA', 'Moldova', 'MD'),
('MCO', 'Monaco', 'MC'),
('MNG', 'Mongolia', 'MN'),
('MSR', 'Montserrat', 'MS'),
('MOZ', 'Mozambique', 'MZ'),
('MMR', 'Myanmar', 'MM'),
('NAM', 'Namibia', 'NA'),
('NRU', 'Nauru', 'NR'),
('NPL', 'Nepal', 'NP'),
('NIC', 'Nicaragua', 'NI'),
('NER', 'Niger', 'NE'),
('NGA', 'Nigeria', 'NG'),
('NIU', 'Niue', 'NU'),
('NFK', 'Norfolk Island', 'NF'),
('NOR', 'Norway', 'NO'),
('CIV', 'Cote dIvoire', 'CI'),
('OMN', 'Oman', 'OM'),
('PAK', 'Pakistan', 'PK'),
('PLW', 'Palau', 'PW'),
('PAN', 'Panama', 'PA'),
('PNG', 'Papua New Guinea', 'PG'),
('PRY', 'Paraguay', 'PY'),
('PER', 'Peru', 'PE'),
('PCN', 'Pitcairn', 'PN'),
('MNP', 'Northern Mariana Islands', 'MP'),
('PRT', 'Portugal', 'PT'),
('PRI', 'Puerto Rico', 'PR'),
('POL', 'Poland', 'PL'),
('GNQ', 'Equatorial Guinea', 'GQ'),
('QAT', 'Qatar', 'QA'),
('FRA', 'France', 'FR'),
('GUF', 'French Guiana', 'GF'),
('PYF', 'French Polynesia', 'PF'),
('REU', 'Reunion', 'RE'),
('ROM', 'Romania', 'RO'),
('RWA', 'Rwanda', 'RW'),
('SWE', 'Sweden', 'SE'),
('SHN', 'Saint Helena', 'SH'),
('KNA', 'Saint Kitts and Nevis', 'KN'),
('LCA', 'Saint Lucia', 'LC'),
('VCT', 'Saint Vincent and the Grenadines', 'VC'),
('SPM', 'Saint Pierre and Miquelon', 'PM'),
('DEU', 'Germany', 'DE'),
('SLB', 'Solomon Islands', 'SB'),
('ZMB', 'Zambia', 'ZM'),
('WSM', 'Samoa', 'WS'),
('SMR', 'San Marino', 'SM'),
('STP', 'Sao Tome and Principe', 'ST'),
('SAU', 'Saudi Arabia', 'SA'),
('SEN', 'Senegal', 'SN'),
('SYC', 'Seychelles', 'SC'),
('SLE', 'Sierra Leone', 'SL'),
('SGP', 'Singapore', 'SG'),
('SVK', 'Slovakia', 'SK'),
('SVN', 'Slovenia', 'SI'),
('SOM', 'Somalia', 'SO'),
('LKA', 'Sri Lanka', 'LK'),
('SDN', 'Sudan', 'SD'),
('FIN', 'Finland', 'FI'),
('SUR', 'Suriname', 'SR'),
('SWZ', 'Swaziland', 'SZ'),
('CHE', 'Switzerland', 'CH'),
('SYR', 'Syria', 'SY'),
('TJK', 'Tajikistan', 'TJ'),
('TWN', 'Taiwan', 'TW'),
('TZA', 'Tanzania', 'TZ'),
('DNK', 'Denmark', 'DK'),
('THA', 'Thailand', 'TH'),
('TGO', 'Togo', 'TG'),
('TKL', 'Tokelau', 'TK'),
('TON', 'Tonga', 'TO'),
('TTO', 'Trinidad and Tobago', 'TT'),
('TCD', 'Chad', 'TD'),
('CZE', 'Czech Republic', 'CZ'),
('TUN', 'Tunisia', 'TN'),
('TUR', 'Turkey', 'TR'),
('TKM', 'Turkmenistan', 'TM'),
('TCA', 'Turks and Caicos Islands', 'TC'),
('TUV', 'Tuvalu', 'TV'),
('UGA', 'Uganda', 'UG'),
('UKR', 'Ukraine', 'UA'),
('HUN', 'Hungary', 'HU'),
('URY', 'Uruguay', 'UY'),
('NCL', 'New Caledonia', 'NC'),
('NZL', 'New Zealand', 'NZ'),
('UZB', 'Uzbekistan', 'UZ'),
('BLR', 'Belarus', 'BY'),
('WLF', 'Wallis and Futuna', 'WF'),
('VUT', 'Vanuatu', 'VU'),
('VAT', 'Holy See (Vatican City State)', 'VA'),
('VEN', 'Venezuela', 'VE'),
('RUS', 'Russian Federation', 'RU'),
('VNM', 'Vietnam', 'VN'),
('EST', 'Estonia', 'EE'),
('USA', 'United States', 'US'),
('VIR', 'Virgin Islands, U.S.', 'VI'),
('ZWE', 'Zimbabwe', 'ZW'),
('PSE', 'Palestine', 'PS'),
('ATA', 'Antarctica', 'AQ'),
('BVT', 'Bouvet Island', 'BV'),
('IOT', 'British Indian Ocean Territory', 'IO'),
('SGS', 'South Georgia and the South Sandwich Islands', 'GS'),
('HMD', 'Heard Island and McDonald Islands', 'HM'),
('ATF', 'French Southern territories', 'TF'),
('UMI', 'United States Minor Outlying Islands', 'UM');
